version: '3.8'

services:
  # PostgreSQL база даних
  postgres:
    image: postgres:15-alpine
    container_name: revit_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - revit_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis для кешування та сесій
  redis:
    image: redis:7-alpine
    container_name: revit_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - revit_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: revit_backend
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      CRYPTOMUS_API_KEY: ${CRYPTOMUS_API_KEY}
      CRYPTOMUS_MERCHANT_ID: ${CRYPTOMUS_MERCHANT_ID}
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - revit_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend сервер
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: revit_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "3000:80"
    networks:
      - revit_network

  # Nginx як reverse proxy
  nginx:
    image: nginx:alpine
    container_name: revit_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - revit_network

volumes:
  postgres_data:
  redis_data:

networks:
  revit_network:
    driver: bridge