"""Initial migration

Revision ID: aeb9da48c2ba
Revises: '6e4918e8a2fd'
Create Date: 2025-08-21 21:56:56.387277+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb9da48c2ba'
down_revision = '6e4918e8a2fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###