"""Initial migration

Revision ID: 6e4918e8a2fd
Revises: 'c8b16be6f5e9'
Create Date: 2025-08-21 21:19:10.167834+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4918e8a2fd'
down_revision = 'c8b16be6f5e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###