"""Add creator applications table

Revision ID: 273cdda0170e
Revises: 'aeb9da48c2ba'
Create Date: 2025-08-23 02:41:15.453569+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273cdda0170e'
down_revision = 'aeb9da48c2ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###