"""Add icon to Collection model

Revision ID: 735aef9e011c
Revises: '273cdda0170e'
Create Date: 2025-08-24 00:37:10.234807+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735aef9e011c'
down_revision = '273cdda0170e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorites')
    op.add_column('collections', sa.Column('icon', sa.String(length=10), nullable=True))
    op.drop_constraint('creator_applications_user_id_fkey', 'creator_applications', type_='foreignkey')
    op.create_foreign_key(None, 'creator_applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'creator_applications', type_='foreignkey')
    op.create_foreign_key('creator_applications_user_id_fkey', 'creator_applications', 'users', ['user_id'], ['id'])
    op.drop_column('collections', 'icon')
    op.create_table('user_favorites',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='user_favorites_product_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_favorites_user_id_fkey', ondelete='CASCADE')
    )
    # ### end Alembic commands ###